### ISSUE TITLE
Haunted Castle : Music inconsistent with arcade

### ISSUE THREAD

**Issue by Zekkele** [jotego/jtcores#426] opened 2023-11-10 01:12 UTC
Music does not sound correct when compared to Arcade pcb.

**Comment by jotego** [comment] 2023-11-10 10:10
Thanks for reporting it. Can you be a bit more specific about what feels different?

**Comment by Zekkele** [comment] 2023-11-10 20:42
Sound channel balance seems off. I think its that the Mid range instruments are way too loud?

**Comment by jotego** [comment] 2024-01-14 17:36
Confirmed in f8166fbb. The problem is in the SCC module. Bug introduced in 3363231b0b0f283e8165027ab4ebb9c7e2565ac9. Fixed in 6c07bb6e.
I will update the files next Friday. Thanks for reporting this.

**Closed** 2024-01-14 17:35 UTC
