### ISSUE TITLE
Outrun: vertical white line in middle of screen

### ISSUE THREAD

**Issue by theenemy-thd** [jotego/jtcores#558] opened 2024-02-20 08:25 UTC
This vertical white line appears down the middle of the screen at the start of the race when the car spins in and the guy waves the flag .. it does disappear quickly but its very annoying
Rgds
Alex

**Comment by jotego** [comment] 2024-02-20 18:20
Indeed. There is probably a missing _video off_ signal that must be connected. I'll look into it.

**Comment by jotego** [comment] 2024-02-24 10:35
The video enable signals were disconnected for debugging purposes. After connecting them back in the JTSHANON and JTOUTRUN cores, the video works as expected.
@theenemy-thd thanks for spotting this. It is fixed in 38014369198bcd6161a60b9267b5d3a9f29fcb8b and will be released in the next JTFRIDAY update

**Comment by theenemy-thd** [comment] 2024-05-04 11:57
Seems while the in game white vert line is fixed it does the same thing after you play a game and after scores are shown

**Comment by jotego** [comment] 2024-05-04 18:16
I cannot see that. Could you please check the version you are running a provide a screen shot? Thanks

**Comment by theenemy-thd** [comment] 2024-05-06 10:56
![20240506_115253](https://github.com/jotego/jtcores/assets/78659007/7a7590a4-219d-416f-b3d2-b251bd945406)
![Screenshot_20240506_115136_Gallery](https://github.com/jotego/jtcores/assets/78659007/0d3f7eb0-b8fe-4084-87bb-435657968a33)
![Screenshot_20240506_115114_Gallery](https://github.com/jotego/jtcores/assets/78659007/5d0c0e55-0a69-4051-b7c4-ee29d4a4c622)

Here happens after you die and enter your name then it goes back to the outrun screen

**Comment by jotego** [comment] 2024-05-06 11:17
Thank you for the screen shots. I cannot reproduce this issue, nor have I seen it during development. It might be your ROM set or some old configuration file. Try deleting configuration files related to Out Run. Also try with a different ROM dump.

**Comment by theenemy-thd** [comment] 2024-05-10 17:31
Deleted everything to do with outrun and ran update all ... still has that white line after score screen shown.

Are you sure tou are starting a game and then dying ... allow it just to go through it screens and after it shows the score table (don't press anything) it show the line as per pics

**Comment by jotego** [comment] 2024-05-12 14:51
I was able to reproduce it. I think this is genuine. The hardware does have a bit that disables the video output and the game normally uses it so there is no video produced while the game makes a screen that takes extra time. It seems like that transition needs a long time but the software does not enable the bit.

The behavior is the same in MAME. Maybe older versions of the game have it fixed.

I do not think it is a core issue. Thank for reporting it.

**Closed by jotego** 2024-05-12 14:51 UTC
Labels: core bug

**Comment by theenemy-thd** [comment] 2024-05-12 19:47
Ahhh ok, well if it happens on real hardware then all fine then

Thanks for looking into it so quickly

**Comment by jotego** [comment] 2024-05-13 04:47
Thank you for looking for footage of the real board.
